### ISSUE TITLE
Thanks a lot for you Project. But I face one problem when I 

### ISSUE THREAD

**Issue by newjbl** [Davideddu/python-apds9930#1]
I face one problem when I "import apds9930" in my openwrt, it is "no module named 'smbus'". 
I try to install the python-smbus but failed. 
do you know how to install the python-smbus to openwrt system. And i think if your project contain the smbus, it is better.

thanks a lot.

**Comment by depau** [comment]
I think you forgot to describe your problem 😂

**Comment by depau** [comment]
My project does not and will not contain the smbus module. If your distro package does not work you can try to download it from pip. `smbus-cffi` and `smbus2` should both work, the latter should be the best.

**Comment by depau** [comment]
I'm closing this as it's not an actual issue.

**Comment by newjbl** [comment]
you are right, and thanks a lot.
